Algoritmo "Operaçaoes matematicas"

Var
A,B : inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval ("Digite um valor para A:")
leia(A)

escreval("Digite um valor para B:")
leia(B)


escreval("Resultado da soma:",A+B)
escreval("Resultado da subtração:",A-B)
escreval("Resultado da divisão:",A/B)
escreval("Resultado da mutiplicação:",A*B)





Fimalgoritmo